# Generated by Django 5.1 on 2024-08-20 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='recipe_id',
            field=models.ForeignKey(db_column='recipe_id', on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe'),
        ),
        migrations.AlterField(
            model_name='steps',
            name='recipe_id',
            field=models.ForeignKey(db_column='recipe_id', on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe'),
        ),
    ]
